### ISSUE TITLE
There isn't any playtime being shown in GOG Galaxy 2.0

### ISSUE THREAD

**Issue by Rishi-T** [jshackles/RetroGOG#8]
I followed the instructions and integrated everything I need successfully but there isn't any playtime being shown in the launcher itself.

I see that the achievements aren't working yet (can't wait for it btw) and I'm assuming playtime is also somehow connected to the retroachievements website.

Also, thanks a lot for this tool dude, made my emulation experience a whole lot better!

**Comment by Pab10Suarez** [comment]
are you sure you did this step correctly? 

> "Navigate to Settings, click on Saving, go to the last option there Save runtime log (aggregate) and turn it on."

i had the same issue because i forgot this important step

**Comment by Rishi-T** [comment]
My bad, I already installed RetroArch properly so I didn't bother reading the instructions under that section.

Issue's resolved, thanks a lot Pab10Suarez!
